### ISSUE TITLE
Add a description in the GitHub repository

### ISSUE THREAD

**Issue by zenorocha** [Polymer/core-layout-trbl#2]

**Comment by zenorocha** [comment]
:up:

**Comment by zenorocha** [comment]
:up:

**Comment by addyosmani** [comment]
@zenorocha Is there a reason all of these old issues are being repinged with the same message? Almost all of the core and paper elements are going to be rewritten for 0.8 and so adding descriptions to these repos now would be premature.

**Comment by zenorocha** [comment]
The only reason is for them to have a relevant description on CE.io so other people can understand what it is about and maybe use it.

![screen shot 2015-02-24 at 10 47 52 am](https://cloud.githubusercontent.com/assets/398893/6350441/9b4ee170-bc12-11e4-98cd-3e7cea77bf04.png)
